/**
* @author chris.heath@synapticap.com
* @date 03/16/2020
*
* @group Assigned_Clinician__c
*
* @description To Initate the Assigned_ClinicianTriggerHandler Class
* Please check ITrigger and TriggerFactory to understand the order execution and method used. DO NOT EDIT THIS FILE
*/
trigger Assigned_ClinicianTrigger on Assigned_Clinician__c (before insert, before update, before delete, after insert, after update, after delete, after undelete) {
	TriggerFactory.createHandler(Assigned_Clinician__c.sObjectType); 
}