/**
* @group Discharge_Section__c
*
* @description To Initate the DischargeSection_TriggerHandler Class
* Please check ITrigger and TriggerFactory to understand the order execution and method used. DO NOT EDIT THIS FILE
*/
trigger DischargeSection_Trigger on Discharge_Section__c (before insert, before update, before delete, after insert, after update, after delete, after undelete) {
    TriggerFactory.createHandler(Discharge_Section__c.sObjectType); 
}