/**
* @group Discharge_Disposition__c
*
* @description To Initate the DischargeDisposition_TriggerHandler Class
* Please check ITrigger and TriggerFactory to understand the order execution and method used. DO NOT EDIT THIS FILE
*/
trigger DischargeDisposition_Trigger on Discharge_Disposition__c (before insert, before update, before delete, after insert, after update, after delete, after undelete) {
    TriggerFactory.createHandler(Discharge_Disposition__c.sObjectType); 
}