/**
* @group Group_Note
*
* @description To Initate the GroupNote_TriggerHandler Class
* Please check ITrigger and TriggerFactory to understand the order execution and method used. DO NOT EDIT THIS FILE
*/
trigger GroupNote_Trigger on Group_Note__c (before insert, before update, before delete, after insert, after update, after delete, after undelete) {
	TriggerFactory.createHandler(Group_Note__c.sObjectType); 
}