/**
* @group Procedure_Order__c
*
* @description To Initate the Procedure_OrderTriggerHandler Class
* Please check ITrigger and TriggerFactory to understand the order execution and method used. DO NOT EDIT THIS FILE
*/
trigger Procedure_OrderTrigger on Procedure_Order__c (before insert, before update, before delete, after insert, after update, after delete, after undelete) {
	if(Trigger.isUpdate && Trigger.isAfter) {
		Procedure_OrderTriggerHandler.SendLabOrder();
	}
	TriggerFactory.createHandler(Procedure_Order__c.sObjectType); 
}