/**
* @group Procedure_Result__c
*
* @description To Initate the Procedure_ResultTriggerHandler Class
* Please check ITrigger and TriggerFactory to understand the order execution and method used. DO NOT EDIT THIS FILE
*/
trigger Procedure_ResultTrigger on Procedure_Result__c (before insert, before update, before delete, after insert, after update, after delete, after undelete) {
	TriggerFactory.createHandler(Procedure_Result__c.sObjectType); 
}