/**
* @group Psych_Testing_Request__c
*
* @description To Initate the PsychTestingRequest_TriggerHandler Class
* Please check ITrigger and TriggerFactory to understand the order execution and method used. DO NOT EDIT THIS FILE
*/
trigger PsychTestingRequest_Trigger on Psych_Testing_Request__c (before insert, before update, before delete, after insert, after update, after delete, after undelete) {
	if(Trigger.isUpdate && Trigger.isAfter) {
		Psych_Testing_RequestTriggerHandler.handlePsychTestRequestChanges();
	}
	TriggerFactory.createHandler(Psych_Testing_Request__c.sObjectType); 
}