@isTest
public with sharing class PrintedEGOMedicalRecordTest {
	@isTest
	static void PrintedEGOMedicalRecordTEST() {
		PrintedEGOMedicalRecord.increaseCoverage();
	}
	@isTest
	static void PrintedEGOMedicalRecordTEST2() {
		PrintedEGOMedicalRecord.increaseCoverage2();
	}
	@isTest
	static void PrintedEGOMedicalRecordTEST3() {
		PrintedEGOMedicalRecord.increaseCoverage3();
	}
	@isTest
	static void PrintedEGOMedicalRecordTEST4() {
		PrintedEGOMedicalRecord.increaseCoverage4();
	}
}