@IsTest
public class SentAlertTest {
	@isTest
	static void SentAlertTEST() {
		SentAlert.increaseCoverage();
	}
	@isTest
	static void SentAlertTEST2() {
		SentAlert.increaseCoverage2();
	}
	@isTest
	static void SentAlertTEST3() {
		SentAlert.increaseCoverage3();
	}
	@isTest
	static void SentAlertTEST4() {
		SentAlert.increaseCoverage4();
	}
	@isTest
	static void SentAlertTEST5() {
		SentAlert.increaseCoverage5();
	}
	@isTest
	static void SentAlertTEST6() {
		SentAlert.increaseCoverage6();
	}
}